### ISSUE TITLE
Plugin stopped working with Atom .208 or so

### ISSUE THREAD

**Issue by alexandernst** [abe33/atom-color-highlight#100]
After Atom .208 (maybe .209) scrolling a CSS file wouldn't cause the colored CSS colors move.

**Comment by abe33** [comment]
Yep, I no longer maintain this package, it have been replaced by [pigments](http://atom.io/packages/pigments). Same features, but better performances ;).

**Comment by alexandernst** [comment]
@abe33 Oh, nice to know :)
Does the same apply to minimap-pigments?

**Comment by abe33** [comment]
Exactly, minimap-pigments replaces minimap-color-highlight ;)
