### ISSUE TITLE
Highlights doesnt show on variables in other files

### ISSUE THREAD

**Issue by dawidk92** [abe33/atom-color-highlight#103]
Plugin highlights variables which was declared in the same file, but in other files it doesnt working.

File with variables:
![zrzut ekranu 2015-07-09 o 17 03 19](https://cloud.githubusercontent.com/assets/7023167/8598723/a7374f0e-265c-11e5-9b96-e4521cbd8c50.png)

Other file:
![zrzut ekranu 2015-07-09 o 17 03 51](https://cloud.githubusercontent.com/assets/7023167/8598728/ad64dd4c-265c-11e5-84f0-5a95f143dfa1.png)

**Comment by abe33** [comment]
Hi, this package have been unpublished and replaced by [pigments](http://atom.io/packages/pigments). Originally, variables were highlighted in other files only when the `project-palette-finder` package was installed. Pigments now includes features from both packages.
