### ISSUE TITLE
Colors are fixed on scroll

### ISSUE THREAD

**Issue by gandhiShepard** [abe33/atom-color-highlight#105]
I'm not sure if this issue is this this plugin or if it's caused by my theme, but colors are are staying in a fixed location. So when I scroll the colors don't move. They stay in a fixed location and overlay the code. Any thoughts on this? Thanks, Stay awesome!

**Comment by gandhiShepard** [comment]
<img width="463" alt="screen shot 2015-07-23 at 10 44 46 am" src="https://cloud.githubusercontent.com/assets/8546059/8854879/e39c82ae-3127-11e5-9fd0-be99a80fcb23.png">

**Comment by gandhiShepard** [comment]
I tried changing themes and still had the same problem.

**Comment by gandhiShepard** [comment]
Happens regardless of language or preprocessor being used.

**Comment by gandhiShepard** [comment]
Ugh! Never mind. I see that you have Pigments out now. I just switched to that and it works like a MF Dream! Thanks! Stay awesome!

**Comment by abe33** [comment]
Yes, this package was unpublished and replaced by pigments, it did not make much sense to split the functionality of displaying colors in two packages.
