### ISSUE TITLE
Colors are sticky

### ISSUE THREAD

**Issue by cbstodd** [abe33/atom-color-highlight#106]
When scrolling down the page the background colors are sticky.  They do not scroll with the content, they hover the page. 
![screen shot 2015-08-04 at 8 57 59 am](https://cloud.githubusercontent.com/assets/5274093/9061036/f432e2a8-3a86-11e5-8a56-90bcbf94acb4.png)

**Comment by abe33** [comment]
Hi @cbstodd, this package have been replaced by [pigments](http://atom.io/packages/pigments). It's the same features (and more) but with better performances and integrated with [project-palette-finder](http://atom.io/packages/project-palette-finder).
