### ISSUE TITLE
Colors show up in incorrect places after loading then scrolling the file

### ISSUE THREAD

**Issue by Maelstrome26** [abe33/atom-color-highlight#107]
There is currently a bug where If you load a .css file, and then scroll down, the color highlights don't move correctly with the content.

This only occurs with color highlights that are also visible on page load. New highlights that aren't visible upon scrolling also don't highlight either.

![colorissue](https://cloud.githubusercontent.com/assets/1776058/9249498/3a927e92-41bd-11e5-9a62-619f3fc898ed.png)

In the above example, I've scrolled down so that the #fff declaration is hidden from view, and the color should be hidden, and the #CCC was present on load, which should have been repositioned. The #6f1b3d code should also now be highlighted, as that originally wasn't in view on page load, but now is.

**Comment by abe33** [comment]
Hi @Maelstrome26, please see #106

**Comment by Maelstrome26** [comment]
Ahh my bad. I should have looked harder when I installed.

**Comment by abe33** [comment]
It's weird you could install it, I was pretty sure to have unpublished it. I'll have to check that.
