### ISSUE TITLE
Highlighted colors stay in place after pasting

### ISSUE THREAD

**Issue by rockerest** [abe33/atom-color-highlight#53]
When there's a few highlighted colors in some content, if you paste a bunch of content above it, those highlights are left in place, breaking a number of things - as you might expect.

So for example:
`row 1, col 10 = "#FF0000;"`
`row 5, col 35 = "#CCCCCC;"`

Paste in `Moby Dick` at row 1, col 1.
Row 1, col 10 and row 5, col 35 still have the color content.

I have found that scrolling many times fixes it (with a scroll wheel, in my experience), while dragging the scrollbar does not fix it.

**Comment by olegshilov** [comment]
![screen shot 2015-06-06 at 01 36 32](https://cloud.githubusercontent.com/assets/930121/8016513/ee833eac-0bec-11e5-9cde-f483097a6d93.png)

**Comment by silvestreh** [comment]
Probably related? I'm seeing this on Atom 0.207.0. atom-color-highlight version is 3.0.9.

![atom-color-highlight_bug](https://cloud.githubusercontent.com/assets/1133339/8026331/dd002166-0d47-11e5-89b2-bbeeeb1413f6.gif)

**Comment by silvestreh** [comment]
@olegshilov I just noticed this package is unmaintained. You should switch to [pigments](https://atom.io/packages/pigments) as I did (same author.)

**Comment by abe33** [comment]
@olegshilov, it's like @silvestreh said, I rewrote this package in `pigments`, and v0.205 or v0.206 (not sure which one) introduced tiled rendering for the editor, changing the way it handle scroll, pigments is already up-to-date.

I initially planned to unpublish this package, as well as `project-palette-finder`, when Atom hit 1.0, but maybe I'll do it sooner as it's now broken.

**Comment by olegshilov** [comment]
@abe33 thanks. now i'll use `pigments`.

**Comment by rockerest** [comment]
Superceded by https://github.com/abe33/atom-pigments

Issue closed-DEPRECATED -> USE PIGMENTS
