### ISSUE TITLE
Uncaught type errors thrown when working with .svg files

### ISSUE THREAD

**Issue by afischer** [abe33/atom-color-highlight#73]
Atom Version: 0.170.0
System: OS X 10.10.1 build 14B25 (Yosemite on MacBookPro6,2)
Thrown From: atom-color-highlight package

Hey there, thanks for the awesome package.   
I'm currently working with a .svg file, and am using your package for the first time. Many TypeErrors are being thrown. Currently throwing:  

- Uncaught TypeError: undefined is not a function (see #61, [stacktrace](http://pastebin.com/raw.php?i=25jy3p9Z)), thrown seven or eight times.
- Uncaught TypeError: undefined is not a function (I think this is new, [stacktrace](http://pastebin.com/raw.php?i=pnmJxE0Y))

**Comment by abe33** [comment]
Hmm, yes I should have seen it coming. The latest patch fixes deprecations towards the release of Atom 1.0 API, I think atom 0.174 introduced new deprecations that I fixed without thinking of prior versions. My best advice is to update to the latest version of Atom. I can fix those issues, bu the result is that I'll write a patch that will have to be removed with 1.0. The main effort for every one is to stabilize things toward 1.0 release, but in the meantime many thing will break and I think it's better that we avoid dealing with too much versions support for the time being (versions > 1.0 are another story).

**Comment by ramaboo** [comment]
.picker {
  font-size: 16px;
  text-align: left;
  line-height: 1.2;
  color: #000000;
  position: absolute;
  z-index: 10000;
  user-select: none;
}


.picker__input {
  cursor: default;
  &.picker__input--active {
    border-color: #0089ec;
  }
}



.picker__holder {
  width: 100%;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}



.picker {
  width: 100%;
}


.picker__holder {
  position: absolute;
  background: #ffffff;
  border: 1px solid #aaaaaa;
  border-top-width: 0;
  border-bottom-width: 0;
  border-radius: 0 0 5px 5px;
  box-sizing: border-box;
  min-width: 176px;
  max-width: 466px;
  max-height: 0;

  opacity: 0;
  -webkit-transform: translateY(-1em) perspective(600px) rotateX(10deg);
  transform: translateY(-1em) perspective(600px) rotateX(10deg);
  -webkit-transition: -webkit-transform 0.15s ease-out, opacity 0.15s ease-out, max-height 0s 0.15s, border-width 0s 0.15s;
  transition: transform 0.15s ease-out, opacity 0.15s ease-out, max-height 0s 0.15s, border-width 0s 0.15s;
}


.picker__frame {
  padding: 1px;
}

.picker__wrap {
  margin: -1px;
}

/**
 * When the picker opens...
 */

.picker--opened .picker__holder {
  max-height: 25em;
  opacity: 1;
  border-top-width: 1px;
  border-bottom-width: 1px;
  -webkit-transform: translateY(0) perspective(600px) rotateX(0);
  transform: translateY(0) perspective(600px) rotateX(0);
  -webkit-transition: -webkit-transform 0.15s ease-out, opacity 0.15s ease-out, max-height 0s, border-width 0s;
  transition: transform 0.15s ease-out, opacity 0.15s ease-out, max-height 0s, border-width 0s;
  box-shadow: 0 6px 18px 1px rgba(0, 0, 0, 0.12);
}

file also cause that bug!
