### ISSUE TITLE
Support for #AARRGGBB format

### ISSUE THREAD

**Issue by jesdga95** [abe33/atom-color-highlight#74]
Android XML color highlight is not officially supported, I guess, however, could we have a feature to highlight #AARRGGBB format?, I guess it should work for web as well. ![captura de pantalla de 2015-01-29 09 16 21](https://cloud.githubusercontent.com/assets/778141/5958946/cf5e1d26-a797-11e4-9652-f41d4e99cac1.png)

#RRGGBB works fine

![captura de pantalla de 2015-01-29 09 20 41](https://cloud.githubusercontent.com/assets/778141/5958992/47e8c2be-a798-11e4-9223-684425fe1446.png)

**Comment by jesdga95** [comment]
Adding this to color-expressions seems to do the trick. Still would like an official solution :)
```js
  Color.addExpression('css_hexa_8', "#(" + hexa + "{8})(?![\\d\\w])", function(color, expression) {
    var _, _ref2;
    _ref2 = this.onigRegExp.exec(expression), _ = _ref2[0], hexa = _ref2[1];
    return color.hexARGB = hexa;
  });
```

**Comment by abe33** [comment]
Thanks for the report, I'll try publishing a patch soon
