### ISSUE TITLE
Issue with coloring SCSS or Stylus color functions

### ISSUE THREAD

**Issue by mehcode** [abe33/atom-color-highlight#79]
Image says it all

![screenshot from 2015-02-10 11 50 56](https://cloud.githubusercontent.com/assets/753919/6135183/60a9bb28-b11b-11e4-8177-46dc954f4b7f.png)

**Comment by abe33** [comment]
Which version of the package do you have installed? This problem was fixed with the latest release (3.0.8).

**Comment by mehcode** [comment]
@abe33 Just updated and yes, this is fixed in the latest version. Thank you for the awesome package.
