### ISSUE TITLE
Color highlighting fixed styling?

### ISSUE THREAD

**Issue by visualcookie** [abe33/atom-color-highlight#94]
Hi,

I got a problem with the package. The color highlighting is somehow fixed. When I scroll, they just stay, where the variables were defined.

You can find a screen below.

OS: Mac OS X

![screenatom](https://cloud.githubusercontent.com/assets/1857554/8033731/2156cd30-0de1-11e5-81d2-30b978d9daae.jpg)

**Comment by abe33** [comment]
I no longer maintain this package, all its features are now available in [pigments](http://atom.io/packages/pigments), which was updated to fix that issue.

I needed a complete rewrite to better integrate with `project-palette-finder` features (which are also included in pigments) and make the whole more efficient.
