### ISSUE TITLE
colored text glued to the screen on scrolling

### ISSUE THREAD

**Issue by rubyconvict** [abe33/atom-color-highlight#99]
![zrzut ekranu 2015-06-17 o 21 15 16](https://cloud.githubusercontent.com/assets/34706/8216339/3d91cf70-1536-11e5-88ba-c806722c1d83.png)

├── atom-color-highlight@3.0.9

$ atom -v
0.209.0

**Comment by wrannaman** [comment]
use pigments 

https://github.com/abe33/atom-pigments

**Comment by rubyconvict** [comment]
Cool, thanks!
